---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - edgenetworktopologies
  - microserviceapplications
  - volumeallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - edgenetworktopologies/finalizers
  - microserviceapplications/finalizers
  - volumeallocations/finalizers
  verbs:
  - update
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - edgenetworktopologies/status
  - microserviceapplications/status
  - volumeallocations/status
  verbs:
  - get
  - patch
  - update
