# This rule is not used by the project joint-ms-data-scheduling itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the crd.cs.phd.uqtr.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: joint-ms-data-scheduling
    app.kubernetes.io/managed-by: kustomize
  name: volumeallocation-editor-role
rules:
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - volumeallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - volumeallocations/status
  verbs:
  - get
