# This rule is not used by the project joint-ms-data-scheduling itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to crd.cs.phd.uqtr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: joint-ms-data-scheduling
    app.kubernetes.io/managed-by: kustomize
  name: volumeallocation-viewer-role
rules:
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - volumeallocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.cs.phd.uqtr
  resources:
  - volumeallocations/status
  verbs:
  - get
